### PR TITLE
[WIP] filter query results

### LINKED ISSUE #42: Filter query/scan results
Is there a way to apply a filter to query/scan results?

### PR DESCRIPTION
**Pull request by ayoub-benali**
This an attempt to fix #42 
For the moment I added 'andFilter' clause and AndFilterCondition class but they don't seem handled correctly yet.

@philwills I would need some pointers if possible to know why my `andFilter('stuff >= 1)` in the tests isn't picked up by the implicits :/ 
The query example that I added in the test is always a `KeyEquals`

### CODE REVIEW

**Comment by philwills** [comment]
Sorry I haven't had a chance to look at this properly yet.

**Comment by nemccarthy** [comment]
Could we also add filters on scans

**Comment by philwills** [comment]
@nemccarthy I'd certainly favour a solution which worked for scans as well as queries.

Hoping to get some time to have a proper look at this soon.

**Comment by ayoub-benali** [comment]
this mainly a first try to get a feeling how things should be done in order to get the filters working. Once that done it should not be a problem to add them for the scans

**Comment by philwills** [comment]
Sorry @ayoub-benali, I meant to try and provide some proper feedback on this, but ended up going in quite a different direction, which resulted in #102

**Pull request closed without merging**
