### PR TITLE
Cats 1.0.0-MF changes

### PR DESCRIPTION
**Pull request by rstradling**
To achieve this change `traverseU` was changed to `traverse`. 

Updated to scala 2.11.11 so partial unification was available.

### CODE REVIEW

**Comment by rstradling** [comment]
Whether this should PR to master and how you want to handle this PR and subsequent release, I leave up to further discussion.

**Comment by 4lex1v** [comment]
Hello!
May i ask if there's any chance to get this merge in the nearest future? Unfortunately this is the only piece left that blocks us from moving towards Cats 1.0 MF.

**Comment by philwills** [comment]
Hi all, sorry for the delay. Went on holiday just around the time this came in. 

This looks good to me, so I'm going to merge this into master now and look to put out some kind of 1.0 type release soon.

**Comment by NoOrdInaryGuy** [comment]
@phillills Awesome news - thanks for this - and also happy to hear about a potential 1.0 release :+1:

**Comment by philwills** [comment]
I've just opened #137 to discuss what I'm proposing for releasing this.

**Comment by philwills** [comment]
This is now released as `1.0.0-M1`. Thanks again for the contribution.

**Pull request merged**
